import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SupabaseProvider from '@/providers/SupabaseProvider.tsx';
import UserProvider from '@/providers/UserProvider.tsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-black`}>
                <SupabaseProvider>
                    <UserProvider>{children}</UserProvider>
                </SupabaseProvider>
            </body>
        </html>
    );
}
